/*
 * File: app/view/ChartPortlet.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ChartPortlet', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.chartportlet',

    requires: [
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.Legend'
    ],

    isPortlet: true,
    cls: 'x-portlet',
    frame: true,
    height: 300,
    layout: {
        type: 'fit'
    },
    closable: true,
    collapsible: true,
    title: 'Chart Portlet',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            draggable: {
                moveOnDrag: false
            },
            items: [
                {
                    xtype: 'chart',
                    shadow: false,
                    insetPadding: 20,
                    store: 'ChartStore',
                    axes: [
                        {
                            type: 'Numeric',
                            fields: [
                                'djia'
                            ],
                            title: 'Dow Jones Average',
                            position: 'left'
                        },
                        {
                            type: 'Numeric',
                            fields: [
                                'sp500'
                            ],
                            grid: false,
                            position: 'right',
                            title: 'S&P 500'
                        }
                    ],
                    series: [
                        {
                            type: 'line',
                            axis: 'left',
                            xField: 'name',
                            yField: 'djia',
                            fill: true,
                            showMarkers: false,
                            smooth: 3,
                            style: {
                                'stroke-width': 1,
                                stroke: 'rgb(148, 174, 10)'
                            }
                        },
                        {
                            type: 'line',
                            axis: 'right',
                            xField: 'name',
                            yField: 'sp500',
                            showMarkers: false,
                            smooth: 3,
                            style: {
                                'stroke-width': 1,
                                stroke: 'rgb(17, 95, 166)'
                            }
                        }
                    ],
                    legend: {

                    }
                }
            ]
        });

        me.callParent(arguments);
    }

});