/*
 * File: app/view/GridPortlet.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GridPortlet', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.gridportlet',

    isPortlet: true,
    cls: 'x-portlet',
    draggable: {
        moveOnDrag: false
    },
    frame: true,
    height: 300,
    closable: true,
    collapsible: true,
    title: 'Grid Portlet',
    store: 'GridStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'company',
                    flex: 1,
                    text: 'Company'
                },
                {
                    xtype: 'numbercolumn',
                    renderer: function(val) {
                        if (val > 0) {
                            return '<span style="color:green;">' + val + '</span>';
                        } else if (val < 0) {
                            return '<span style="color:red;">' + val + '</span>';
                        }
                        return val;
                    },
                    width: 75,
                    dataIndex: 'change',
                    text: 'Change'
                },
                {
                    xtype: 'numbercolumn',
                    renderer: function(val) {
                        if (val > 0) {
                            return '<span style="color:green;">' + val + '%</span>';
                        } else if (val < 0) {
                            return '<span style="color:red;">' + val + '%</span>';
                        }
                        return val;
                    },
                    width: 75,
                    dataIndex: 'pctChange',
                    text: '% Change'
                }
            ]
        });

        me.callParent(arguments);
    }

});