/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    views: [
        'Portal',
        'PortalPanel',
        'SimplePortlet',
        'ChartPortlet',
        'GridPortlet',
        'Message'
    ],

    refs: [
        {
            autoCreate: true,
            ref: 'msg',
            selector: 'message',
            xtype: 'message'
        }
    ],

    onPortletBeforeClose: function(panel, eOpts) {
        // Provide a custom fade out effect when a portlet is removed from the portal
        if (!panel.closing) {
            panel.closing = true;
            panel.el.animate({
                opacity: 0,
                callback: panel.doClose,
                scope: panel
            });
        }
        return false;

    },

    onPortletClose: function(panel, eOpts) {
        this.showMsg('"' + panel.title + '" was removed');
    },

    showMsg: function(msg) {
        var msgId = Ext.id(),
            msgCmp = this.getMsg();

        this.msgId = msgId;
        msgCmp.update(msg);
        msgCmp.show();

        Ext.defer(this.clearMsg, 3000, this, [msgId]);
    },

    clearMsg: function(msgId) {
        if (msgId === this.msgId) {
            this.getMsg().hide();
        }
    },

    init: function(application) {
        this.control({
            "panel[isPortlet]": {
                beforeclose: this.onPortletBeforeClose,
                close: this.onPortletClose
            }
        });
    }

});
